'use client';

import React, { useState, useEffect } from 'react';
import { MainLayout } from '@/components/MainLayout';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabase';

export default function ConsentPage() {
  const router = useRouter();
  const [consent1, setConsent1] = useState(false);
  const [consent2, setConsent2] = useState(false);
  const [consent3, setConsent3] = useState(false);
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  useEffect(() => {
    // Check if user is authenticated and if they've already completed intake
    const checkAuthAndIntake = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        router.push('/auth');
        return;
      }
      
      setIsAuthenticated(true);

      // Check if user has already completed intake - if so, redirect to dashboard
      const { data: intakeRecord } = await supabase
        .from('intake')
        .select('intake_data')
        .eq('user_id', session.user.id)
        .maybeSingle();

      const intake = intakeRecord?.intake_data;
      const hasCompletedIntake = intake && 
        intake.demographics && 
        intake.medical && 
        intake.lifestyle && 
        intake.goals &&
        Object.keys(intake.demographics).length > 0 &&
        Object.keys(intake.medical).length > 0 &&
        Object.keys(intake.lifestyle).length > 0 &&
        Object.keys(intake.goals).length > 0;

      if (hasCompletedIntake) {
        console.log('User already completed intake, redirecting to dashboard');
        localStorage.setItem('consent_given', 'true');
        localStorage.setItem('intake_completed', 'true');
        router.push('/dashboard');
      }
    };
    
    checkAuthAndIntake();
  }, [router]);

  const handleContinue = () => {
    if (consent1 && consent2 && consent3) {
      localStorage.setItem('consent_given', 'true');
      router.push('/intake');
    }
  };

  const allConsented = consent1 && consent2 && consent3;

  if (!isAuthenticated) {
    return null;
  }

  return (
    <MainLayout>
      <div className="container mx-auto px-4 py-8 sm:py-16">
        <div className="max-w-3xl mx-auto">
          <Card className="bg-slate-800/50 border-slate-700 p-4 sm:p-8">
            <h1 className="text-2xl sm:text-3xl font-bold text-cyan-400 mb-2">
              Research Consent & Acknowledgment
            </h1>
            <p className="text-sm sm:text-base text-slate-400 mb-6 sm:mb-8">
              Please read and acknowledge the following before proceeding
            </p>

            <div className="space-y-6 mb-8">
              <div className="p-6 bg-amber-900/20 border border-amber-700 rounded-lg">
                <h2 className="text-xl font-semibold text-amber-400 mb-3">
                  ⚠️ RESEARCH / DEMO PURPOSES ONLY — NOT MEDICAL ADVICE
                </h2>
                <p className="text-slate-300 mb-4">
                  This platform is designed exclusively for research, educational, and demonstration 
                  purposes. It does not provide medical advice, diagnosis, or treatment recommendations.
                </p>
              </div>

              <div className="space-y-4">
                <div className="flex items-start gap-3 p-4 bg-slate-900/50 rounded-lg">
                  <Checkbox
                    id="consent1"
                    checked={consent1}
                    onCheckedChange={(checked) => setConsent1(checked as boolean)}
                    className="mt-1"
                  />
                  <Label htmlFor="consent1" className="text-slate-300 cursor-pointer flex-1">
                    <strong className="text-cyan-400">I understand</strong> that this platform is 
                    for research and demonstration purposes only, and does not provide medical advice 
                    or treatment recommendations.
                  </Label>
                </div>

                <div className="flex items-start gap-3 p-4 bg-slate-900/50 rounded-lg">
                  <Checkbox
                    id="consent2"
                    checked={consent2}
                    onCheckedChange={(checked) => setConsent2(checked as boolean)}
                    className="mt-1"
                  />
                  <Label htmlFor="consent2" className="text-slate-300 cursor-pointer flex-1">
                    <strong className="text-cyan-400">I acknowledge</strong> that any information 
                    or suggestions generated by this platform should not be used to make medical 
                    decisions, and I will consult qualified healthcare professionals for any 
                    health-related concerns.
                  </Label>
                </div>

                <div className="flex items-start gap-3 p-4 bg-slate-900/50 rounded-lg">
                  <Checkbox
                    id="consent3"
                    checked={consent3}
                    onCheckedChange={(checked) => setConsent3(checked as boolean)}
                    className="mt-1"
                  />
                  <Label htmlFor="consent3" className="text-slate-300 cursor-pointer flex-1">
                    <strong className="text-cyan-400">I agree</strong> to use this platform for 
                    educational purposes only and understand that the peptides discussed may be 
                    research-only substances with varying regulatory statuses and potential risks.
                  </Label>
                </div>
              </div>
            </div>

            <div className="flex gap-4">
              <Button
                onClick={() => router.push('/auth')}
                variant="outline"
                className="border-slate-600 text-slate-300 hover:bg-slate-700"
              >
                Go Back
              </Button>
              <Button
                onClick={handleContinue}
                disabled={!allConsented}
                className="flex-1 bg-cyan-600 hover:bg-cyan-700 text-white disabled:opacity-50 disabled:cursor-not-allowed"
              >
                I Understand & Continue
              </Button>
            </div>
          </Card>
        </div>
      </div>
    </MainLayout>
  );
}

